sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build tex/your_file_1.tex
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build tex/your_file_2.tex
deploy:
  provider: releases
  api_key:
    secure: XbNPDH1YIwz548o/cMVXwbHfT6UqVKibFH9/yLbY/49wYlFI9dXah3WhiEsKRC+Hb46Wo+OtGVFRd701B6s/t9hHB9cGb+qgtJzTu6SjC7tCQ+JCHVqLycYtgh50ojkGpxXBlZw0NAHqNZYle7WCHbCDmbN+3dZyw7UgxZJpltFsPj+u5SaecKiB9uT+gfqfierO/ipRekbNHUAJRhv1WsFyWQw6QPfNLy/p1pM/P4enqXj/WFAiKPOeWRlK87HaPJJZ6CPUtxchz4q1tphCsQ2KTwoPP8yfhCgz5RxvPD9b9/boSWqM5wQtqdS8AmH5cHm6MRDI/yeXnSMIL9LmJvR3m9oXdc+FUTdnFUk58aNjXWeDlOs8ltw3xmPQY8tRTICb7qiVybOFZf2K99yk5WW/78eLcAgLb5b4lHNdHkO0tM5TyxNPzlT3o7ObkDhnh0yQbBe+KzcJMFuUhkLfCMoNV/JU/iyCQIoNJS2wREgMsC/AVcPUfTIefmaExc26QDlUfz34itcXddjrgaSizfyhjjuqbcbqX/uTXvIFsbiID/9bS32rJQ0ZlRovVoUGzw63WKeAD+xcKLzZI6VIlD+XqsIaloEtSEqpcHDKVw0agZKwdHijYvBA7uAINuCnkbhplqmyAc2XaHLM2OUjQDjGCjdW0G39cFC1yx6RDkc=
  file:
  - _build/your_file_1.pdf
  - _build/your_file_2.pdf
  on:
    repo: ogajduse/bp_generator_kybernetickych_utoku
